AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create the service and task on ECS cluster
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: 'JavaSample-Service'
      Cpu: 256
      Memory: 512
      TaskRoleArn: 'arn:aws:iam::743550917294:role/ecsTaskExecutionRole'
      ContainerDefinitions:
        - Cpu: 256
          Memory: 512
          Image: 743550917294.dkr.ecr.us-east-1.amazonaws.com/javasample:latest
          Name: 'JavaSample-Container'
          PortMappings: 
            - ContainerPort: 8080
              HostPort: 80
  TargetGroup:              
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 6
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Name: 'Java-Sample-Service'
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue 'VPC'
  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref 'TargetGroup'
          Type: 'forward'
      Conditions:
        - Field: path-pattern
          Values: 
            - '*'
      ListenerArn: !ImportValue 'Listener'
      Priority: 1      
  Service:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      Cluster: !ImportValue 'Cluster'
      ServiceName: 'JavaSample-Service'
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: 1
      TaskDefinition: !Ref 'TaskDefinition' 
      LoadBalancers:
        - ContainerName: JavaSample-Container
          ContainerPort: 8080
          TargetGroupArn: !Ref 'TargetGroup'
