AWSTemplateFormatVersion: '2010-09-09'
Description: for container cluster on ECS, loadbalancer, Security group and cloudwatch

Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: 'java-sample-CF'
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: java-sample-load-balancer
      Subnets:
        - !ImportValue 'Subnet1'
        - !ImportValue 'Subnet2'
      SecurityGroups: 
        - !Ref 'LoadBalancerSecurityGroup'
  LoadBalancerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: security group for loadbalancer to services on ECS
      VpcId: !ImportValue 'VPC'
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: -1
  DefaultTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'    
    Properties:
      Name: Default
      VpcId: !ImportValue 'VPC'
      Protocol: 'HTTP'
      Port: 80
