AWSTemplateFormatVersion: '2010-09-09'
Description: container on ECS
Resources:
  Task:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: javasample
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !ImportValue 'ECSTaskExecutionRole'
      ContainerDefinitions:
        - Name: javasample
          Image: 743550917294.dkr.ecr.us-east-1.amazonaws.com/javasample:latest
          Cpu: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 'javasamplelogs'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'javasample'
  ListenerRule:
    Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'  
    Properties:
      ListenerArn: !ImportValue Listener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: Forward
  TargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: javasample-tg
      VpcId: !ImportValue VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-209
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      TargetType: ip
