AWSTemplateFormatVersion: '2010-09-09'
Description: VPC for ECS containers

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
  Subnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      CidrBlock: !Sub '10.0.0.0/20'
  Subnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Sub '10.0.32.0/20'
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'

  VpcGatewayAttachment:
    Type: 'AWS::EC2::VpcGatewayAttachment'
    InternetGatewayId: !Ref InternetGateway
    VpcId: !Ref VPC
